# Generated by Django 2.1 on 2018-08-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_marks_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dep_name',
            new_name='department_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sub_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dep_id',
        ),
        migrations.AddField(
            model_name='department',
            name='department_id',
            field=models.CharField(default='ans', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='course_id',
            field=models.ForeignKey(default='ans', on_delete=django.db.models.deletion.CASCADE, to='student.Course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department_id',
            field=models.ForeignKey(default='ans', on_delete=django.db.models.deletion.CASCADE, to='student.Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='course_id',
            field=models.ForeignKey(default='ans', on_delete=django.db.models.deletion.CASCADE, to='student.Course'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course_id',
            field=models.ForeignKey(default='ans', on_delete=django.db.models.deletion.CASCADE, to='student.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(default='ans', on_delete=django.db.models.deletion.CASCADE, to='student.Course'),
        ),
    ]
