# Generated by Django 2.1 on 2018-08-16 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180816_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Course'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Department'),
        ),
    ]
